import type { CountryConfig } from './types.js';

export const config: CountryConfig = {
  code: 'EUR',
  name: 'Eurozone',
  currency: 'EUR',
  region: 'Europe',
  centralBank: 'European Central Bank',
  indicators: [
    {
      id: 'eur-refi-rate',
      label: 'ECB Main Refi Rate',
      category: 'policy_rate',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      policyRateKey: 'EUR',
    },
    {
      id: 'eur-core-hicp',
      label: 'Core HICP YoY',
      category: 'inflation',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      macroReadingKey: 'ez-core-hicp',
    },
    {
      id: 'eur-de10y',
      label: 'DE 10Y Bund Yield',
      category: 'yields',
      frequency: 'daily',
      isPrimary: true,
      tier: 'fast',
      tvSymbol: 'TVC:DE10Y',
    },
    {
      id: 'eur-btp-bund-spread',
      label: 'BTP-Bund Spread',
      category: 'fiscal',
      frequency: 'daily',
      isPrimary: true,
      tier: 'fast',
      computedSpread: { symbol1: 'TVC:IT10Y', symbol2: 'TVC:DE10Y' },
    },
    {
      id: 'eur-unemployment',
      label: 'Eurozone Unemployment',
      category: 'labor',
      frequency: 'monthly',
      isPrimary: false,
      tier: 'slow',
      macroReadingKey: 'ez-unemployment',
    },
    {
      id: 'eur-de-ifo',
      label: 'German IFO',
      category: 'sentiment',
      frequency: 'monthly',
      isPrimary: false,
      tier: 'slow',
      macroReadingKey: 'de-ifo',
    },
    {
      id: 'eur-composite-pmi',
      label: 'EZ Composite PMI',
      category: 'growth',
      frequency: 'monthly',
      isPrimary: false,
      tier: 'slow',
      macroReadingKey: 'ez-composite-pmi',
    },
  ],
  keyAnchors: [
    'ECB rate path',
    'German fiscal expansion',
    'Peripheral spread dynamics',
    'Energy import dependency',
  ],
  structuralForces: [
    'Fragmented fiscal policy across member states creates divergent credit risk',
    'German industrial model undergoing structural transition',
    'ECB must balance core disinflation against peripheral fiscal sustainability',
  ],
  dependencies: [
    {
      countryCode: 'USD',
      relationship: 'Policy divergence',
      whyNow: 'ECB-Fed rate differential is the primary EURUSD driver',
    },
    {
      countryCode: 'CHF',
      relationship: 'Safe-haven flows',
      whyNow: 'EURCHF reflects eurozone stress levels',
    },
  ],
  sources: [
    {
      id: 'eur-ecb-press-conf',
      title: 'ECB Monetary Policy Press Conference — March 2026',
      publisher: 'European Central Bank',
      kind: 'policy',
      url: 'https://www.ecb.europa.eu/press/pressconf/html/index.en.html',
      publishedAt: '2026-03-06',
      whyItMatters: 'Forward guidance signals on rate trajectory and quantitative tightening pace',
      extracts: [
        'Inflation continues to decline but services inflation remains elevated',
        'The Governing Council will follow a data-dependent and meeting-by-meeting approach',
      ],
    },
    {
      id: 'eur-ec-forecast',
      title: 'European Commission Winter Economic Forecast',
      publisher: 'European Commission',
      kind: 'macro',
      url: 'https://economy-finance.ec.europa.eu/economic-forecast-and-surveys/economic-forecasts_en',
      publishedAt: '2026-02-13',
      whyItMatters: 'Official growth and inflation projections shape fiscal policy expectations',
      extracts: [
        'GDP growth projected at 1.2% for 2026, an upgrade from the autumn forecast',
      ],
    },
  ],
};
