import type { CountryConfig } from './types.js';

export const config: CountryConfig = {
  code: 'JPY',
  name: 'Japan',
  currency: 'JPY',
  region: 'Asia-Pacific',
  centralBank: 'Bank of Japan',
  indicators: [
    {
      id: 'jpy-policy-rate',
      label: 'BoJ Policy Rate',
      category: 'policy_rate',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      policyRateKey: 'JPY',
    },
    {
      id: 'jpy-core-core-cpi',
      label: 'Core-Core CPI YoY',
      category: 'inflation',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      macroReadingKey: 'jp-core-core-cpi',
    },
    {
      id: 'jpy-usdjpy',
      label: 'USDJPY',
      category: 'intervention',
      frequency: 'daily',
      isPrimary: true,
      tier: 'fast',
      tvSymbol: 'OANDA:USDJPY',
    },
    {
      id: 'jpy-jgb-10y',
      label: 'JGB 10Y Yield',
      category: 'yields',
      frequency: 'daily',
      isPrimary: true,
      tier: 'fast',
      tvSymbol: 'TVC:JP10Y',
    },
    {
      id: 'jpy-trade-balance',
      label: 'Trade Balance',
      category: 'trade',
      frequency: 'monthly',
      isPrimary: false,
      tier: 'slow',
      macroReadingKey: 'jp-trade-balance',
    },
  ],
  keyAnchors: [
    'BoJ normalization pace',
    'MoF intervention threshold',
    'JGB yield curve control legacy',
    'Wage-price virtuous cycle',
  ],
  structuralForces: [
    'Decades of ultra-loose policy make normalization path uniquely sensitive',
    'Carry trade unwinds can trigger sharp JPY rallies and cross-asset volatility',
    'Demographic headwinds limit long-run growth potential',
  ],
  dependencies: [
    {
      countryCode: 'USD',
      relationship: 'Rates differential',
      whyNow: 'US-Japan yield gap is the dominant USDJPY driver',
    },
    {
      countryCode: 'AUD',
      relationship: 'Risk proxy and trade flows',
      whyNow: 'AUDJPY is a key risk sentiment barometer in Asia-Pacific',
    },
  ],
  sources: [
    {
      id: 'jpy-boj-outlook',
      title: 'BoJ Outlook for Economic Activity and Prices — January 2026',
      publisher: 'Bank of Japan',
      kind: 'policy',
      url: 'https://www.boj.or.jp/en/mopo/outlook/index.htm',
      publishedAt: '2026-01-24',
      whyItMatters: 'Reveals BoJ confidence in achieving sustainable 2% inflation target',
      extracts: [
        'Underlying CPI inflation is expected to increase gradually',
        'The virtuous cycle between wages and prices has been strengthening',
      ],
    },
    {
      id: 'jpy-mof-fx',
      title: 'MoF Foreign Exchange Intervention Record',
      publisher: 'Ministry of Finance Japan',
      kind: 'market',
      url: 'https://www.mof.go.jp/english/policy/international_policy/reference/feio/index.htm',
      publishedAt: '2026-02-07',
      whyItMatters: 'Tracks actual and verbal intervention — key for USDJPY tail risk',
      extracts: [
        'Authorities continue to monitor FX market movements with a high sense of urgency',
      ],
    },
  ],
};
