import type { CountryConfig } from './types.js';

export const config: CountryConfig = {
  code: 'USD',
  name: 'United States',
  currency: 'USD',
  region: 'North America',
  centralBank: 'Federal Reserve',
  indicators: [
    {
      id: 'usd-fed-funds',
      label: 'Fed Funds Rate',
      category: 'policy_rate',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      policyRateKey: 'USD',
    },
    {
      id: 'usd-core-cpi',
      label: 'Core CPI YoY',
      category: 'inflation',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      macroReadingKey: 'us-core-cpi',
    },
    {
      id: 'usd-core-pce',
      label: 'Core PCE YoY',
      category: 'inflation',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      macroReadingKey: 'us-core-pce',
    },
    {
      id: 'usd-nfp',
      label: 'NFP Monthly Change',
      category: 'labor',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      macroReadingKey: 'us-nfp',
    },
    {
      id: 'usd-unemployment',
      label: 'Unemployment Rate',
      category: 'labor',
      frequency: 'monthly',
      isPrimary: true,
      tier: 'slow',
      macroReadingKey: 'us-unemployment',
    },
    {
      id: 'usd-us02y',
      label: '2Y Treasury Yield',
      category: 'yields',
      frequency: 'daily',
      isPrimary: true,
      tier: 'fast',
      tvSymbol: 'TVC:US02Y',
    },
    {
      id: 'usd-us10y',
      label: '10Y Treasury Yield',
      category: 'yields',
      frequency: 'daily',
      isPrimary: true,
      tier: 'fast',
      tvSymbol: 'TVC:US10Y',
    },
    {
      id: 'usd-ism-mfg',
      label: 'ISM Manufacturing',
      category: 'sentiment',
      frequency: 'monthly',
      isPrimary: false,
      tier: 'slow',
      macroReadingKey: 'us-ism-mfg',
    },
    {
      id: 'usd-initial-claims',
      label: 'Initial Claims',
      category: 'labor',
      frequency: 'weekly',
      isPrimary: false,
      tier: 'medium',
      macroReadingKey: 'us-initial-claims',
    },
    {
      id: 'usd-2s10s-spread',
      label: '2Y/10Y Spread',
      category: 'yields',
      frequency: 'daily',
      isPrimary: false,
      tier: 'fast',
      computedSpread: { symbol1: 'TVC:US10Y', symbol2: 'TVC:US02Y' },
    },
  ],
  keyAnchors: [
    'Fed reaction function',
    'Tariff pass-through',
    'Treasury supply',
    'USD liquidity',
  ],
  structuralForces: [
    'Reserve-currency demand makes USD a funding and stress currency',
    'Twin deficits keep fiscal credibility in the frame',
    'Trade policy changes inflation, growth, and geopolitical leverage simultaneously',
  ],
  dependencies: [
    {
      countryCode: 'JPY',
      relationship: 'Rates and safe-haven interaction',
      whyNow: 'US yields remain the cleanest driver of USDJPY',
    },
    {
      countryCode: 'EUR',
      relationship: 'Policy divergence',
      whyNow: 'Fed vs ECB path drives EURUSD direction',
    },
  ],
  sources: [
    {
      id: 'usd-fomc-statement',
      title: 'FOMC Statement — March 2026',
      publisher: 'Federal Reserve',
      kind: 'policy',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
      publishedAt: '2026-03-12',
      whyItMatters: 'Sets the tone for near-term rate expectations and forward guidance language',
      extracts: [
        'The Committee decided to maintain the target range for the federal funds rate',
        'Economic activity has been expanding at a moderate pace',
      ],
    },
    {
      id: 'usd-beige-book',
      title: 'Beige Book — March 2026',
      publisher: 'Federal Reserve',
      kind: 'macro',
      url: 'https://www.federalreserve.gov/monetarypolicy/beige-book-default.htm',
      publishedAt: '2026-03-05',
      whyItMatters: 'Anecdotal evidence of regional economic conditions informs FOMC deliberations',
      extracts: [
        'Economic activity expanded slightly across most Districts',
        'Labor markets remained tight with moderate wage growth',
      ],
    },
  ],
};
